DROP TABLE IF EXISTS op_logs;
DROP TABLE IF EXISTS graph_meta;
DROP TABLE IF EXISTS graph_jobs;
DROP TABLE IF EXISTS card_tags;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS card_links;
DROP TABLE IF EXISTS cards;
